#!/bin/bash
pin=5
sudo raspi-gpio set $pin ip pd

pin_read=$(sudo raspi-gpio get $pin | \
awk -F ' ' '{print $3}' | \
awk -F '' '{print $7}')

while [ $pin_read -le 0 ]
do
    pin_read=$(sudo raspi-gpio get $pin | \
    awk -F ' ' '{print $3}' | \
    awk -F '' '{print $7}')
done

echo waiting for removal...

pin_read=$(sudo raspi-gpio get $pin | \
awk -F ' ' '{print $3}' | \
awk -F '' '{print $7}')

while [ $pin_read -ge 1 ]
do
    pin_read=$(sudo raspi-gpio get $pin | \
    awk -F ' ' '{print $3}' | \
    awk -F '' '{print $7}')
done

echo Starting game

echo go > /dev/udp/192.168.0.144/9999 # TODO: Change to correct IP and port