#!/bin/bash
pin=5
sudo pinctrl set $pin ip pd

pin_read=$(sudo pinctrl get $pin | awk -F ' ' '{print $5}')

while [ "$pin_read" = "lo" ]
do
    pin_read=$(sudo pinctrl get $pin | awk -F ' ' '{print $5}')
done

echo waiting for removal...

pin_read=$(sudo pinctrl get $pin | awk -F ' ' '{print $5}')

while [ "$pin_read" = "hi" ]
do
    pin_read=$(sudo pinctrl get $pin | awk -F ' ' '{print $5}')
done

echo Starting game

echo go > /dev/udp/172.20.10.8/9999 # TODO: Change to correct IP and port
